//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABITACION()
        {
            this.RECEPCIONs = new HashSet<RECEPCION>();
        }
    
        public int IdHabitacion { get; set; }
        public string Numero { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> IdEstadoHabitacion { get; set; }
        public Nullable<int> IdPiso { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ESTADO_HABITACION ESTADO_HABITACION { get; set; }
        public virtual PISO PISO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPCION> RECEPCIONs { get; set; }
    }
}
