//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEPCION()
        {
            this.VENTAs = new HashSet<VENTA>();
        }
    
        public int IdRecepcion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdHabitacion { get; set; }
        public Nullable<System.DateTime> FechaEntrada { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.DateTime> FechaSalidaConfirmacion { get; set; }
        public Nullable<decimal> PrecioInicial { get; set; }
        public Nullable<decimal> Adelanto { get; set; }
        public Nullable<decimal> PrecioRestante { get; set; }
        public Nullable<decimal> TotalPagado { get; set; }
        public Nullable<decimal> CostoPenalidad { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual HABITACION HABITACION { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA> VENTAs { get; set; }
    }
}
